name: Compatibility CI workflow

on:
  push:
    branches:
      - develop
      - release/**
      - feature/**
    pull_request:
      branches:
        - master
        - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: ['12', '14']
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: '0'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
